#!/usr/bin/env python3
"""
Interactive configuration tool for Paper Finder
"""
import os
from pathlib import Path
from typing import Optional

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt, Confirm
from rich.table import Table
from rich.markdown import Markdown

console = Console()


def get_env_path() -> Path:
    """Get the .env file path"""
    return Path.cwd() / ".env"


def load_existing_config() -> dict:
    """Load existing configuration from .env file"""
    env_path = get_env_path()
    config = {}
    
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    config[key.strip()] = value.strip()
    
    return config


def save_config(config: dict):
    """Save configuration to .env file"""
    env_path = get_env_path()
    
    with open(env_path, 'w') as f:
        f.write("# Paper Finder Configuration\n")
        f.write("# Auto-generated by configure.py\n\n")
        
        if config.get('OPENAI_API_KEY'):
            f.write("# OpenAI API Key for semantic ranking and query expansion\n")
            f.write(f"OPENAI_API_KEY={config['OPENAI_API_KEY']}\n\n")
        
        if config.get('SEMANTIC_SCHOLAR_API_KEY'):
            f.write("# Semantic Scholar API Key (optional, increases rate limits)\n")
            f.write(f"SEMANTIC_SCHOLAR_API_KEY={config['SEMANTIC_SCHOLAR_API_KEY']}\n\n")
        
        if config.get('ZOTERO_API_KEY'):
            f.write("# Zotero Integration\n")
            f.write(f"ZOTERO_API_KEY={config['ZOTERO_API_KEY']}\n")
            f.write(f"ZOTERO_USER_ID={config.get('ZOTERO_USER_ID', '')}\n")
            f.write(f"ZOTERO_LIBRARY_TYPE={config.get('ZOTERO_LIBRARY_TYPE', 'user')}\n\n")
    
    console.print(f"[green]✓[/green] Configuration saved to {env_path}")


def display_current_config(config: dict):
    """Display current configuration"""
    table = Table(title="Current Configuration", show_header=True)
    table.add_column("Setting", style="cyan")
    table.add_column("Status", style="green")
    
    table.add_row(
        "OpenAI API Key",
        "✓ Configured" if config.get('OPENAI_API_KEY') else "✗ Not set"
    )
    table.add_row(
        "Semantic Scholar API Key",
        "✓ Configured" if config.get('SEMANTIC_SCHOLAR_API_KEY') else "✗ Not set (optional)"
    )
    table.add_row(
        "Zotero API Key",
        "✓ Configured" if config.get('ZOTERO_API_KEY') else "✗ Not set"
    )
    table.add_row(
        "Zotero User ID",
        config.get('ZOTERO_USER_ID', '✗ Not set') if config.get('ZOTERO_USER_ID') else "✗ Not set"
    )
    
    console.print(table)


def configure_openai(config: dict) -> dict:
    """Configure OpenAI settings"""
    console.print("\n[bold cyan]OpenAI Configuration[/bold cyan]")
    console.print("Used for AI-powered semantic ranking and query expansion.")
    console.print("Get your API key from: [link]https://platform.openai.com/api-keys[/link]\n")
    
    current = config.get('OPENAI_API_KEY', '')
    if current:
        console.print(f"Current key: {current[:15]}...{current[-4:]}")
        if not Confirm.ask("Update OpenAI API key?", default=False):
            return config
    
    api_key = Prompt.ask("Enter OpenAI API Key (or leave empty to skip)", default="")
    if api_key:
        config['OPENAI_API_KEY'] = api_key
    
    return config


def configure_semantic_scholar(config: dict) -> dict:
    """Configure Semantic Scholar settings"""
    console.print("\n[bold cyan]Semantic Scholar Configuration[/bold cyan]")
    console.print("Optional: Increases API rate limits for paper searches.")
    console.print("Get your API key from: [link]https://www.semanticscholar.org/product/api[/link]\n")
    
    current = config.get('SEMANTIC_SCHOLAR_API_KEY', '')
    if current:
        console.print(f"Current key: {current[:15]}...{current[-4:]}")
        if not Confirm.ask("Update Semantic Scholar API key?", default=False):
            return config
    
    api_key = Prompt.ask("Enter Semantic Scholar API Key (or leave empty to skip)", default="")
    if api_key:
        config['SEMANTIC_SCHOLAR_API_KEY'] = api_key
    
    return config


def configure_zotero(config: dict) -> dict:
    """Configure Zotero settings"""
    console.print("\n[bold cyan]Zotero Configuration[/bold cyan]")
    console.print("Enables direct export of papers to your Zotero library.")
    console.print("Get your API key from: [link]https://www.zotero.org/settings/keys[/link]\n")
    
    current_key = config.get('ZOTERO_API_KEY', '')
    current_user = config.get('ZOTERO_USER_ID', '')
    
    if current_key:
        console.print(f"Current API key: {current_key[:15]}...{current_key[-4:]}")
        console.print(f"Current User ID: {current_user}")
        if not Confirm.ask("Update Zotero settings?", default=False):
            return config
    
    api_key = Prompt.ask("Enter Zotero API Key (or leave empty to skip)", default="")
    if api_key:
        config['ZOTERO_API_KEY'] = api_key
        config['ZOTERO_USER_ID'] = Prompt.ask("Enter Zotero User ID")
        config['ZOTERO_LIBRARY_TYPE'] = Prompt.ask(
            "Library type",
            choices=["user", "group"],
            default="user"
        )
    
    return config


def main():
    """Main configuration flow"""
    console.clear()
    
    # Display banner
    console.print(Panel.fit(
        "[bold cyan]Paper Finder Configuration Tool[/bold cyan]\n"
        "Interactive setup for API keys and integration",
        border_style="cyan"
    ))
    
    # Load existing config
    config = load_existing_config()
    
    # Display current configuration
    console.print("\n")
    display_current_config(config)
    console.print("\n")
    
    # Configuration menu
    while True:
        console.print("\n[bold]Configuration Options:[/bold]")
        console.print("1. Configure OpenAI (AI-powered ranking)")
        console.print("2. Configure Semantic Scholar (optional)")
        console.print("3. Configure Zotero (citation export)")
        console.print("4. View current configuration")
        console.print("5. Save and exit")
        console.print("6. Exit without saving")
        
        choice = Prompt.ask("\nSelect option", choices=["1", "2", "3", "4", "5", "6"])
        
        if choice == "1":
            config = configure_openai(config)
        elif choice == "2":
            config = configure_semantic_scholar(config)
        elif choice == "3":
            config = configure_zotero(config)
        elif choice == "4":
            console.print("\n")
            display_current_config(config)
        elif choice == "5":
            save_config(config)
            console.print("\n[green]Configuration complete![/green]")
            console.print("Run [bold]python paper_finder.py --help[/bold] to get started.\n")
            break
        elif choice == "6":
            if Confirm.ask("Exit without saving changes?", default=False):
                console.print("[yellow]Configuration not saved.[/yellow]")
                break


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        console.print("\n[yellow]Configuration cancelled.[/yellow]")
    except Exception as e:
        console.print(f"\n[red]Error: {e}[/red]")
